
export const SUBMIT_SUPPORT_REQUEST = "APP/Globals/Support/SUBMIT_SUPPORT_REQUEST";
export const SUBMIT_SUPPORT_SUCCESS = "APP/Globals/Support/SUBMIT_SUPPORT_SUCCESS";
export const SUBMIT_SUPPORT_FAILURE = "APP/Globals/Support/SUBMIT_SUPPORT_FAILURE";

export const GET_SUPPORT_TICKETS_REQUEST = "APP/Globals/Support/GET_SUPPORT_TICKETS_REQUEST";
export const GET_SUPPORT_TICKETS_SUCCESS = "APP/Globals/Support/GET_SUPPORT_TICKETS_SUCCESS";
export const GET_SUPPORT_TICKETS_FAILURE = "APP/Globals/Support/GET_SUPPORT_TICKETS_FAILURE";

export const GET_SUPPORT_TICKET_BY_ID_REQUEST = "APP/Globals/Support/GET_SUPPORT_TICKET_BY_ID_REQUEST";
export const GET_SUPPORT_TICKET_BY_ID_SUCCESS = "APP/Globals/Support/GET_SUPPORT_TICKET_BY_ID_SUCCESS";
export const GET_SUPPORT_TICKET_BY_ID_FAILURE = "APP/Globals/Support/GET_SUPPORT_TICKET_BY_ID_FAILURE";

export const CLOSE_SUPPORT_TICKET_BY_ID_REQUEST = "APP/Globals/Support/CLOSE_SUPPORT_TICKET_BY_ID_REQUEST";
export const CLOSE_SUPPORT_TICKET_BY_ID_SUCCESS = "APP/Globals/Support/CLOSE_SUPPORT_TICKET_BY_ID_SUCCESS";
export const CLOSE_SUPPORT_TICKET_BY_ID_FAILURE = "APP/Globals/Support/CLOSE_SUPPORT_TICKET_BY_ID_FAILURE";

export const REPLY_SUPPORT_TICKET_BY_ID_REQUEST = "APP/Globals/Support/REPLY_SUPPORT_TICKET_BY_ID_REQUEST";
export const REPLY_SUPPORT_TICKET_BY_ID_SUCCESS = "APP/Globals/Support/REPLY_SUPPORT_TICKET_BY_ID_SUCCESS";
export const REPLY_SUPPORT_TICKET_BY_ID_FAILURE = "APP/Globals/Support/REPLY_SUPPORT_TICKET_BY_ID_FAILURE";

export const CLEAR_STATE = "APP/Globals/Support/CLEAR_STATE";
export const CLEAR_RESPONSE = "APP/Globals/Support/CLEAR_RESPONSE";

export const GET_OPEN_TICKETS_REQUEST = "APP/Globals/Support/GET_OPEN_TICKETS_REQUEST";
export const GET_OPEN_TICKETS_SUCCESS = "APP/Globals/Support/GET_OPEN_TICKETS_SUCCESS";
export const GET_OPEN_TICKETS_FAILURE = "APP/Globals/Support/GET_OPEN_TICKETS_FAILURE";
