
export const SEND_WALLET_ADDRESS_REQUEST = 'APP/Report/SEND_WALLET_ADDRESS_REQUEST';
export const SEND_WALLET_ADDRESS_SUCCESS = 'APP/Report/SEND_WALLET_ADDRESS_SUCCESS';
export const SEND_WALLET_ADDRESS_FAILURE = 'APP/Report/SEND_WALLET_ADDRESS_FAILURE';

export const GET_NEW_ADDRESS_REQUEST = 'APP/Report/GET_NEW_ADDRESS_REQUEST';
export const GET_NEW_ADDRESS_SUCCESS = 'APP/Report/GET_NEW_ADDRESS_SUCCESS';
export const GET_NEW_ADDRESS_FAILURE = 'APP/Report/GET_NEW_ADDRESS_FAILURE';

export const GET_BALANCE_REQUEST = 'APP/Report/GET_BALANCE_REQUEST';
export const GET_BALANCE_SUCCESS = 'APP/Report/GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'APP/Report/GET_BALANCE_FAILURE';

export const GET_WALLENT_INFO_REQUEST = 'APP/Report/GET_WALLENT_INFO_REQUEST';
export const GET_WALLENT_INFO_SUCCESS = 'APP/Report/GET_WALLENT_INFO_SUCCESS';
export const GET_WALLENT_INFO_FAILURE = 'APP/Report/GET_WALLENT_INFO_FAILURE';

export const CLEAR_MESSAGE = 'app/ReferShare/CLEAR_MESSAGE';
