export const NOTIFICATIONS_FETCH_UNREAD_REQUEST =
  "App/common/AdminNotifications/NOTIFICATIONS_FETCH_UNREAD_REQUEST";
export const NOTIFICATIONS_FETCH_UNREAD_SUCCESS =
  "App/common/AdminNotifications/NOTIFICATIONS_FETCH_UNREAD_SUCCESS";
export const NOTIFICATIONS_FETCH_UNREAD_FAILURE =
  "App/common/AdminNotifications/NOTIFICATIONS_FETCH_UNREAD_FAILURE";

export const NOTIFICATIONS_FETCH_REQUEST =
  "App/common/AdminNotifications/NOTIFICATIONS_FETCH_REQUEST";
export const NOTIFICATIONS_FETCH_SUCCESS =
  "App/common/AdminNotifications/NOTIFICATIONS_FETCH_SUCCESS";
export const NOTIFICATIONS_FETCH_FAILURE =
  "App/common/AdminNotifications/NOTIFICATIONS_FETCH_FAILURE";

export const NOTIFICATIONS_SEEN_REQUEST =
  "App/common/AdminNotifications/NOTIFICATIONS_SEEN_REQUEST";
export const NOTIFICATIONS_SEEN_SUCCESS =
  "App/common/AdminNotifications/NOTIFICATIONS_SEEN_SUCCESS";
export const NOTIFICATIONS_SEEN_FAILURE =
  "App/common/AdminNotifications/NOTIFICATIONS_SEEN_FAILURE";

export const NOTIFICATIONS_READ_UPDATE_REQUEST =
  "App/common/AdminNotifications/NOTIFICATIONS_READ_UPDATE_REQUEST";
export const NOTIFICATIONS_READ_UPDATE_SUCCESS =
  "App/common/AdminNotifications/NOTIFICATIONS_READ_UPDATE_SUCCESS";
export const NOTIFICATIONS_READ_UPDATE_FAILURE =
  "App/common/AdminNotifications/NOTIFICATIONS_READ_UPDATE_FAILURE";

export const NEW_NOTIFICATIONS_COUNT_REQUEST =
  "App/common/AdminNotifications/NEW_NOTIFICATIONS_COUNT_REQUEST";
export const NEW_NOTIFICATIONS_COUNT_SUCCESS =
  "App/common/AdminNotifications/NEW_NOTIFICATIONS_COUNT_SUCCESS";
export const NEW_NOTIFICATIONS_COUNT_FAILURE =
  "App/common/AdminNotifications/NEW_NOTIFICATIONS_COUNT_FAILURE";
