export const RESEND_CONFIRMATION_REQUEST = 'App/UserDashboard/RESEND_CONFIRMATION_REQUEST';
export const RESEND_CONFIRMATION_SUCCESS = 'App/UserDashboard/RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_FAILURE = 'App/UserDashboard/RESEND_CONFIRMATION_FAILURE';

export const CLEAR_STATE = 'App/UserDashboard/CLEAR_STATE';
