export const GET_WATCHONLY_ADDRESS_REQUEST = "APP/containers/WalletAddress/WalletsList/GET_WATCHONLY_ADDRESS_REQUEST";
export const GET_WATCHONLY_ADDRESS_SUCCESS = "APP/containers/WalletAddress/WalletsList/GET_WATCHONLY_ADDRESS_SUCCESS";
export const GET_WATCHONLY_ADDRESS_FAILURE = "APP/containers/WalletAddress/WalletsList/GET_WATCHONLY_ADDRESS_FAILURE";

export const POST_WATCHONLY_WALLET_ADDRESS_REQUEST = "APP/containers/WalletAddress/WalletsList/POST_WATCHONLY_WALLET_ADDRESS_REQUEST";
export const POST_WATCHONLY_WALLET_ADDRESS_SUCCESS = "APP/containers/WalletAddress/WalletsList/POST_WATCHONLY_WALLET_ADDRESS_SUCCESS";
export const POST_WATCHONLY_WALLET_ADDRESS_FAILURE = "APP/containers/WalletAddress/WalletsList/POST_WATCHONLY_WALLET_ADDRESS_FAILURE";

export const CLEAR_STATE = "APP/Containers/WalletAddress/CLEAR_STATE";
