export const GET_REPORT_LISTING_REQUEST = 'API/Report/GET_REPORT_LISTING_REQUEST';
export const GET_REPORT_LISTING_SUCCESS = 'API/Report/GET_REPORT_LISTING_SUCCESS';
export const GET_REPORT_LISTING_FAILURE = 'API/Report/GET_REPORT_LISTING_FAILURE';

export const DOWNLOAD_REPORT_REQUEST = 'API/Report/DOWNLOAD_REPORT_REQUEST';
export const DOWNLOAD_REPORT_SUCCESS = 'API/Report/DOWNLOAD_REPORT_SUCCESS';
export const DOWNLOAD_REPORT_FAILURE = 'API/Report/DOWNLOAD_REPORT_FAILURE';


export const CLEAR_MESSAGE = 'app/ReferShare/CLEAR_MESSAGE';
